<h1>Accueil</h1>


<a href="?page=add">Ajouter un event</a>
<ul>
    <?php foreach ($events as $event) : ?>
        <li><a href="?page=show&id=<?= $event['id'] ?>"><?= $event['title'] ?></a></li>
    <?php endforeach ?>
</ul>

<ul>
    <?php foreach ($categories as $category) : ?>
        <li><a href="?page=category&id=<?= $category['id'] ?>"><?= $category['name'] ?> (<?= $category['totalEvents'] ?>) </a></li>
    <?php endforeach ?>
</ul>